pretrained_model_path: "./ckpt/highway_500"

dataset_config:
  path: "data/highway"
  prompt: "a white van drives by a highway dashcam video with forests on either side," # RENAME Inversion editing_prompts
  n_sample_frame: 8
  sampling_rate: 1
  stride: 80
  offset:
    left: 0
    right: 0
    top: 0
    bottom: 0

editing_config:
  use_invertion_latents: true
  use_inversion_attention: true

  editing_prompts:
    [
      a white van drives by a dashcam on an autumn forrested highway,
      a Scooby Doo Bus drive by a dashcam on a forrested highway,
      a white van drives by a dashcam on a snowy highway,
      a blue FordGT drives by a dashcam on a desert highway,
      a BMW aggressively cuts off a car on a dashcam on a forrested highway,
    ]

  p2p_config:
    0:
      is_replace_controller: False
      cross_replace_steps:
        default_: 0.8
      self_replace_steps: 0.9
      eq_params:
        words: ["autumn", "forrested"]
        values: [10, 10]
      blend_words:
        [["white", "van"], ["dashcam", "autumn", "forrested", "highway"]]
      blend_self_attention: True
      blend_th: [0.3, 0.3]

    1:
      is_replace_controller: True
      cross_replace_steps:
        default_: 0.5
      self_replace_steps: 0.5
      use_inversion_attention: True
      blend_words:
        [["Scooby", "Doo", "Bus"], ["dashcam", "forrested", "highway"]]
      blend_self_attention: True
      blend_th: [0.3, 0.3]

    2:
      is_replace_controller: True
      cross_replace_steps:
        default_: 0.5
      self_replace_steps: 0.5
      use_inversion_attention: True
      blend_words: [["white", "van"], ["dashcam", "snowy", "highway"]]
      blend_self_attention: True
      blend_th: [0.3, 0.3]

    3:
      is_replace_controller: True
      cross_replace_steps:
        default_: 0.5
      self_replace_steps: 0.5
      use_inversion_attention: True
      blend_words: [["blue", "FordGT"], ["dashcam", "desert", "highway"]]
      blend_self_attention: True
      blend_th: [0.3, 0.3]

    4:
      is_replace_controller: True
      cross_replace_steps:
        default_: 0.5
      self_replace_steps: 0.5
      use_inversion_attention: True
      blend_words: ["dashcam", "forrested", "highway"]]
      blend_self_attention: True
      blend_th: [0.3, 0.3]

clip_length: "${..dataset_config.n_sample_frame}"
sample_seeds: [0]
prompt2prompt_edit: True

# DDIM parameters
guidance_scale: 7.5
num_inference_steps: 50

model_config:
  lora: 160

test_pipeline_config:
  target: video_diffusion.pipelines.p2p_ddim_spatial_temporal.P2pDDIMSpatioTemporalPipeline
  num_inference_steps: "${..validation_sample_logger.num_inference_steps}"

seed: 0
